### ISSUE TITLE
Scala 2.12

### ISSUE THREAD

**Issue by alonsodomin** [soc/sbt-testng#4]
What would be needed to make this library compile for 2.12? I made a naive attempt updating the Scala version and ScalaJS plugin but got stuck since, for some reason, the SBT plugin module inisist on resolving a 2.12 version of the ScalaJS SBT plugin:

> Note: Some unresolved dependencies have extra attributes.  Check that these dependencies exist with the requested attributes.
[warn] 		org.scala-js:sbt-scalajs:0.6.13 (scalaVersion=2.12, sbtVersion=0.13)

This is happening regardless of the fact that in the build file the SBT plugin module is overriding the Scala version as 2.10... Any ideas what is happening?

**Comment by soc** [comment]
Mhhh, which command did you use? Are we using sbt-doge in this build? (Sorry, on my phone)

**Comment by alonsodomin** [comment]
oh yes, true. Using SBT doge command it resolves properly... sorry, not really familiar with this kind of partial cross builds

**Comment by soc** [comment]
I really hope this becomes the default in SBT 1.0 ...

**Comment by soc** [comment]
@alonsodomin I published the library for 2.10, 2.11 and 2.12. It should hit the repo shortly.

**Comment by alonsodomin** [comment]
oh great thanks, I saw some tests failures when running sbt doge and, to be honest, that put me off a little bit...

with this and the java locales for ScalaJS already in 2.12, what is left to the get the datetime backport lib in 2.12 too?

ps: feel free to close this whenever you want

**Comment by soc** [comment]
Don't worry, I think the tests are sadly work-in-progress. I think it's mainly some busy work to adjust the reporting in the stub implementation of TestNG for Scala.js.

I'm currently waiting for scala-java-locales to be published for 2.12: https://github.com/cquiroz/scala-java-locales/issues/60

Then I'll release scala-java-time for 2.12, too.

**Comment by soc** [comment]
My mistake, scala-java-locales are already published. Building scala-java-time now ...

**Comment by soc** [comment]
@alonsodomin Followup: https://github.com/soc/scala-java-time/issues/46

**Comment by soc** [comment]
@alonsodomin Sorry about the confusion, by the way, I should really document how this stuff is built and published.

**Comment by alonsodomin** [comment]
no worries @soc, I get there is a lot of hard work to get all the things aligned nicely
